management:
  security:
    enabled: false
  endpoints:
    web:
      exposure.include: "*"
  endpoint:
    health:
      show-details: always
  health:
    binders:
      enabled: true

spring:
  cloud:
    stream:
      kafka:
        binder:
          auto-add-partitions: true
          min-partition-count: 2
      bindings:
        input:
          destination: com.mycompany.bitcoin.api.price
          content-type: application/*+avro
          group: newsClientGroup
          consumer:
            max-attempts: 4
            back-off-initial-interval: 10000
  sleuth:
    sampler.probability: 1.0
#    web.skipPattern: (^cleanup.*|.+favicon.*)

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true